import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
test('cadastro não atribui cargo, vínculos são protegidos e remoção preserva autoria', async () => {
 const db = new PGlite();
 const owner='00000000-0000-0000-0000-000000000001', employee='00000000-0000-0000-0000-000000000002';
 try {
  await db.exec(`create role anon; create role authenticated; create role service_role;
   alter default privileges grant execute on functions to anon,authenticated;
   create schema auth; create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   create function auth.role() returns text language sql stable as $$select current_setting('request.jwt.claim.role',true)$$;
   ${fs.readFileSync(new URL('./fixtures/schema-real.sql',import.meta.url),'utf8')}
   create function forcar_virada_ciclo_teste(uuid) returns text language sql as $$select 'legado'$$;
   create function gerar_codigo_lote(uuid) returns text language sql as $$select 'legado'$$;
   create function gerar_codigo_lote(uuid,varchar) returns text language sql as $$select 'legado'$$;
   create function get_meu_perfil() returns text language sql as $$select 'operador'$$;
   create function get_user_funcao() returns text language sql as $$select 'operador'$$;
   create function get_user_loja_id() returns uuid language sql as $$select null::uuid$$;
   create function usuario_tem_acesso_loja(uuid) returns boolean language sql as $$select true$$;
   create view vw_regua_vencimentos as select codigo_lote from ciclos_lotes;
   grant all on perfis,usuario_lojas,lojas to authenticated;
  `);
  await db.exec(fs.readFileSync(new URL('../supabase/migrations/202609300001_acompanhamento.sql',import.meta.url),'utf8'));
  await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260930174445_acesso_validasuper.sql',import.meta.url),'utf8'));
  await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260930175223_privilegios_e_rotina.sql',import.meta.url),'utf8'));
  await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260930184825_corrigir_colisao_codigo_lote.sql',import.meta.url),'utf8'));
  await db.exec(`create trigger onboarding after insert on auth.users for each row execute function handle_new_user_onboarding();
   create trigger profile after insert on auth.users for each row execute function handle_new_user_profile();
   create trigger legacy after insert on auth.users for each row execute function handle_new_user();
   insert into auth.users(id,raw_user_meta_data) values('${owner}','{"nome":"Responsável","funcao":"administrador","loja_id":"00000000-0000-0000-0000-000000000099"}');
   select set_config('request.jwt.claim.sub','${owner}',false);
   select set_config('request.jwt.claim.role','authenticated',false);
  `);
  const query=async(sql,params)=>(await db.query(sql,params)).rows;
  assert.equal((await query('select funcao from perfis where id=$1',[owner]))[0].funcao,'operador');
  assert.equal((await query('select count(*) n from usuario_lojas'))[0].n,0);
  assert.equal((await query("select has_function_privilege('anon','vs_criar(jsonb)','execute') permitido"))[0].permitido,false);
  assert.equal((await query("select has_function_privilege('authenticated','vs_lote(uuid,text)','execute') permitido"))[0].permitido,false);
  const loja=(await query(`select vs_salvar_loja('{"nome":"Loja teste","numero_loja":"03"}') loja`))[0].loja;
  const loja2=(await query(`select vs_salvar_loja('{"nome":"Outra loja","numero_loja":"3"}') loja`))[0].loja;
  await query('select vs_painel($1)',[loja.id]);
  await query('select vs_painel($1)',[loja2.id]);
  await query('select vs_painel($1)',[loja2.id]);
  const codigos=await query('select codigo_lote,sequencia_num from ciclos_lotes order by sequencia_num');
  assert.equal(codigos.length,2);
  assert.equal(new Set(codigos.map(c=>c.codigo_lote)).size,2);
  assert.deepEqual(codigos.map(c=>c.sequencia_num),[1,2]);
  const diario1=(await query("select codigo_lote from vs_lote($1,'VENC')",[loja.id]))[0].codigo_lote;
  const diario2=(await query("select codigo_lote from vs_lote($1,'VENC')",[loja2.id]))[0].codigo_lote;
  assert.notEqual(diario1,diario2);
  assert.equal((await query("select codigo_lote from vs_lote($1,'VENC')",[loja2.id]))[0].codigo_lote,diario2);
  assert.equal((await query('select funcao from perfis where id=$1',[owner]))[0].funcao,'administrador');
  await db.exec('set role authenticated');
  await assert.rejects(db.exec(`update perfis set funcao='administrador'`),/permission denied/);
  await assert.rejects(db.exec(`insert into usuario_lojas values('${owner}','${loja.id}')`),/permission denied/);
  await assert.rejects(db.exec(`select vs_vincular_membro('${owner}','${employee}','${loja.id}','Teste','operador',null)`),/permission denied/);
  await db.exec('reset role');
  await db.exec(`insert into auth.users(id) values('${employee}')`);
  await query('select vs_vincular_membro($1,$2,$3,$4,$5,null)',[owner,employee,loja.id,'Operador','operador']);
  await db.exec(`select set_config('request.jwt.claim.sub','${employee}',false)`);
  await assert.rejects(query('select vs_editar_perfil($1,$2,$3,$4)',[employee,'Operador','administrador',loja.id]),/próprio cargo/);
  await assert.rejects(query(`select vs_salvar_loja('{"nome":"Escalada"}')`),/Somente administrador/);
  await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false)`);
  await query('select vs_remover_membro($1,$2)',[employee,loja.id]);
  assert.equal((await query('select count(*) n from auth.users where id=$1',[employee]))[0].n,1);
  assert.equal((await query('select loja_id from perfis where id=$1',[employee]))[0].loja_id,null);
  assert.deepEqual((await query("select reloptions from pg_class where relname='vw_regua_vencimentos'"))[0].reloptions,['security_invoker=true']);
 } finally { await db.close(); }
});
